version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependabot
      - dependencies
      - github-actions
      - build
