name: Release
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main
jobs:
  tag:
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      release_name: ${{ steps.generate_tag_name.outputs.release_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Tag Name
        run: |
          export now=$(date -u)
          export tag_name=$(date -d "$now" -u '+%Y%m%d%H%M')
          export release_name=$(date -d "$now" -u '+%Y/%m/%d %H:%M UTC')
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
        id: generate_tag_name
      - name: Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          create_annotated_tag: true
          tag_prefix: v
          custom_tag: ${{ steps.generate_tag_name.outputs.tag_name }}
  build:
    timeout-minutes: 90
    needs:
      - tag
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: false
      group: ${{ format('{0}-{1}', github.event_name, github.ref_name) }}
    container:
      image: docker.io/library/golang:1-alpine
    outputs:
      upstream_latest_tag: ${{ steps.get_latest_tag.outputs.tag }}
    steps:
      - name: Install Dependencies
        run: apk update && apk upgrade && apk add --no-cache jq gcc musl-dev linux-headers
      - name: Get Latest Git Tag
        id: get_latest_tag
        run: |
          export tag=$(wget -qO- https://api.github.com/repos/SagerNet/sing-box/tags | jq -r '.[0].name')
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          go install -trimpath -buildvcs=false -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ steps.get_latest_tag.outputs.tag }}' -extldflags '-static' -s -w -buildid=" -tags 'with_quic with_grpc with_dhcp with_wireguard with_shadowsocksr with_ech with_utls with_reality_server with_acme with_clash_api with_v2ray_api with_gvisor with_embedded_tor with_lwip staticOpenssl staticZlib staticLibevent' github.com/sagernet/sing-box/cmd/sing-box@${{ steps.get_latest_tag.outputs.tag }}
          mv "$(go env GOPATH)/bin/sing-box" ./sing-box
        id: get_path
      - name: Compress Executable
        run: set -ex && wget https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz -O upx-4.0.2-amd64_linux.tar.xz && tar -xvf upx-4.0.2-amd64_linux.tar.xz upx-4.0.2-amd64_linux/upx && mv ./upx-4.0.2-amd64_linux/upx . && ./upx --no-color --mono --no-progress --ultra-brute --no-backup ./sing-box && ./upx --test ./sing-box
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sing-box
          path: ./sing-box
  release:
    timeout-minutes: 10
    needs:
      - tag
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sing-box
      - name: Generate Release Body
        run: |
          echo '# [${{ needs.build.outputs.upstream_latest_tag }}](https://github.com/SagerNet/sing-box/releases/tag/${{ needs.build.outputs.upstream_latest_tag }})' > ./release_body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: release_try_0
        with:
          name: ${{ needs.tag.outputs.release_name }}
          prerelease: false
          body_path: ./release_body.md
          tag_name: ${{ needs.tag.outputs.tag }}
          files: ./sing-box
      - name: Release (Retry 1)
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        if: steps.release_try_0.outcome == 'failure'
        id: release_try_1
        with:
          name: ${{ needs.tag.outputs.release_name }}
          body_path: ./release_body.md
          prerelease: false
          tag_name: ${{ needs.tag.outputs.tag }}
          files: ./sing-box
      - name: Release (Retry 2)
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        if: steps.release_try_1.outcome == 'failure'
        id: release_try_2
        with:
          name: ${{ needs.tag.outputs.release_name }}
          body_path: ./release_body.md
          prerelease: false
          tag_name: ${{ needs.tag.outputs.tag }}
          files: ./sing-box
      - name: Release (Retry 3)
        uses: softprops/action-gh-release@v1
        continue-on-error: false
        if: steps.release_try_2.outcome == 'failure'
        id: release_try_3
        with:
          name: ${{ needs.tag.outputs.release_name }}
          body_path: ./release_body.md
          prerelease: false
          tag_name: ${{ needs.tag.outputs.tag }}
          files: ./sing-box
